/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author diego
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form inicio1
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP_principal = new javax.swing.JPanel();
        encabezado = new javax.swing.JPanel();
        izq = new javax.swing.JPanel();
        button1 = new modelo.Button();
        der = new javax.swing.JPanel(){

        };
        panel_menu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button2 = new modelo.Button();
        button3 = new modelo.Button();
        button4 = new modelo.Button();
        jPanel5 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1180, 700));

        JP_principal.setBackground(new java.awt.Color(255, 255, 255));
        JP_principal.setLayout(new java.awt.BorderLayout());

        encabezado.setBackground(new java.awt.Color(255, 153, 51));
        encabezado.setPreferredSize(new java.awt.Dimension(1180, 100));
        encabezado.setLayout(new java.awt.BorderLayout());

        izq.setBackground(new java.awt.Color(255, 153, 51));
        izq.setPreferredSize(new java.awt.Dimension(200, 100));
        izq.setLayout(new java.awt.BorderLayout());

        button1.setBackground(new java.awt.Color(255, 153, 51));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menu.png"))); // NOI18N
        button1.setColorNormal(new java.awt.Color(255, 153, 51));
        button1.setColorPressed(new java.awt.Color(255, 153, 51));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        izq.add(button1, java.awt.BorderLayout.CENTER);

        encabezado.add(izq, java.awt.BorderLayout.WEST);

        der.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout derLayout = new javax.swing.GroupLayout(der);
        der.setLayout(derLayout);
        derLayout.setHorizontalGroup(
            derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        derLayout.setVerticalGroup(
            derLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        encabezado.add(der, java.awt.BorderLayout.CENTER);

        JP_principal.add(encabezado, java.awt.BorderLayout.NORTH);

        panel_menu.setBackground(new java.awt.Color(255, 153, 51));
        panel_menu.setPreferredSize(new java.awt.Dimension(200, 750));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(0, 86, 179));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        button2.setBackground(new java.awt.Color(255, 153, 51));
        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar.png"))); // NOI18N
        button2.setText("Cerrar Sesion");
        button2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(255, 153, 51));
        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Empleados.png"))); // NOI18N
        button3.setText("Empleados");
        button3.setColorNormal(new java.awt.Color(255, 153, 51));
        button3.setColorPressed(new java.awt.Color(255, 153, 51));
        button3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(255, 153, 51));
        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/envio.png"))); // NOI18N
        button4.setText("Envios");
        button4.setColorNormal(new java.awt.Color(255, 153, 51));
        button4.setColorPressed(new java.awt.Color(255, 153, 51));
        button4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        JP_principal.add(panel_menu, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(980, 508));
        jPanel5.setMinimumSize(new java.awt.Dimension(980, 508));
        jPanel5.setPreferredSize(new java.awt.Dimension(980, 650));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        JP_principal.add(jPanel5, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JP_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JP_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        int posicion = panel_menu.getX();
        if (posicion == 0) {
            // Mover hacia la izquierda
            Animacion.Animacion.mover_izquierda(0, -200, 1, 1, panel_menu);

            // Esperar 300ms y luego ocultar
            new javax.swing.Timer(300, new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    panel_menu.setVisible(false);
                    ((javax.swing.Timer) e.getSource()).stop(); // detener el timer
                }
            }).start();

        } else {
            // Mostrar y mover hacia la derecha
            panel_menu.setVisible(true);
            Animacion.Animacion.mover_derecha(-200, 0, 1, 1, panel_menu);
        }
    }//GEN-LAST:event_button1MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        ILogin l = new ILogin();
        l.setVisible(true);
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(Inicio.this);
        if (w != null) {
            w.dispose(); // cierra el JFrame que contiene este panel
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        Envios e = new Envios();
        JFrame frameGerente = new JFrame("Panel Envios");
        frameGerente.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameGerente.setLayout(new BorderLayout());
        frameGerente.add(e, BorderLayout.CENTER);
        frameGerente.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frameGerente.pack(); 
        frameGerente.setLocationRelativeTo(null);
        frameGerente.setVisible(true);
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(Inicio.this);
        if (w != null) {
            w.dispose(); // cierra el JFrame que contiene este panel
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        Empleados e = new Empleados();
        JFrame frameGerente = new JFrame("Panel Empleados");
        frameGerente.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameGerente.setLayout(new BorderLayout());
        frameGerente.add(e, BorderLayout.CENTER);
        frameGerente.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frameGerente.pack(); 
        frameGerente.setLocationRelativeTo(null);
        frameGerente.setVisible(true);
        java.awt.Window w = javax.swing.SwingUtilities.getWindowAncestor(Inicio.this);
        if (w != null) {
            w.dispose(); // cierra el JFrame que contiene este panel
        }
    }//GEN-LAST:event_button3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_principal;
    private modelo.Button button1;
    private modelo.Button button2;
    private modelo.Button button3;
    private modelo.Button button4;
    private javax.swing.JPanel der;
    private javax.swing.JPanel encabezado;
    private javax.swing.JPanel izq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
